// flow-typed signature: 0b4f3d4c2b76d7693ea1341942c6082d
// flow-typed version: <<STUB>>/eslint-config-zeal_v^0.14.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-zeal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-zeal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-zeal/chai' {
  declare module.exports: any;
}

declare module 'eslint-config-zeal/mocha' {
  declare module.exports: any;
}

declare module 'eslint-config-zeal/react-native' {
  declare module.exports: any;
}

declare module 'eslint-config-zeal/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-zeal/chai.js' {
  declare module.exports: $Exports<'eslint-config-zeal/chai'>;
}
declare module 'eslint-config-zeal/index' {
  declare module.exports: $Exports<'eslint-config-zeal'>;
}
declare module 'eslint-config-zeal/index.js' {
  declare module.exports: $Exports<'eslint-config-zeal'>;
}
declare module 'eslint-config-zeal/mocha.js' {
  declare module.exports: $Exports<'eslint-config-zeal/mocha'>;
}
declare module 'eslint-config-zeal/react-native.js' {
  declare module.exports: $Exports<'eslint-config-zeal/react-native'>;
}
declare module 'eslint-config-zeal/react.js' {
  declare module.exports: $Exports<'eslint-config-zeal/react'>;
}
