// flow-typed signature: b35d6101709e9da2edcdf0df18c81f05
// flow-typed version: <<STUB>>/react-css-themr_v^1.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-css-themr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-css-themr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-css-themr/lib/components/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-css-themr/lib/components/themr' {
  declare module.exports: any;
}

declare module 'react-css-themr/lib/index' {
  declare module.exports: any;
}

declare module 'react-css-themr/lib/utils/themr-shape' {
  declare module.exports: any;
}

declare module 'react-css-themr/src/components/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-css-themr/src/components/themr' {
  declare module.exports: any;
}

declare module 'react-css-themr/src/index' {
  declare module.exports: any;
}

declare module 'react-css-themr/src/utils/themr-shape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-css-themr/lib/components/ThemeProvider.js' {
  declare module.exports: $Exports<'react-css-themr/lib/components/ThemeProvider'>;
}
declare module 'react-css-themr/lib/components/themr.js' {
  declare module.exports: $Exports<'react-css-themr/lib/components/themr'>;
}
declare module 'react-css-themr/lib/index.js' {
  declare module.exports: $Exports<'react-css-themr/lib/index'>;
}
declare module 'react-css-themr/lib/utils/themr-shape.js' {
  declare module.exports: $Exports<'react-css-themr/lib/utils/themr-shape'>;
}
declare module 'react-css-themr/src/components/ThemeProvider.js' {
  declare module.exports: $Exports<'react-css-themr/src/components/ThemeProvider'>;
}
declare module 'react-css-themr/src/components/themr.js' {
  declare module.exports: $Exports<'react-css-themr/src/components/themr'>;
}
declare module 'react-css-themr/src/index.js' {
  declare module.exports: $Exports<'react-css-themr/src/index'>;
}
declare module 'react-css-themr/src/utils/themr-shape.js' {
  declare module.exports: $Exports<'react-css-themr/src/utils/themr-shape'>;
}
