// flow-typed signature: 1e02d25ee5ada31139cee458ce546f56
// flow-typed version: <<STUB>>/redux-devtools-extension_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-extension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-extension' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-extension/developmentOnly' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-extension/developmentOnly.js' {
  declare module.exports: $Exports<'redux-devtools-extension/developmentOnly'>;
}
declare module 'redux-devtools-extension/index' {
  declare module.exports: $Exports<'redux-devtools-extension'>;
}
declare module 'redux-devtools-extension/index.js' {
  declare module.exports: $Exports<'redux-devtools-extension'>;
}
