// flow-typed signature: 2580ebca54732cfb1eb955852c73858b
// flow-typed version: <<STUB>>/zeal-redux-utils_v^0.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zeal-redux-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'zeal-redux-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zeal-redux-utils/lib/__tests__/createActionTypes-spec' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/lib/__tests__/createReducer-spec' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/lib/createActionTypes' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/lib/createReducer' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/lib/index' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/src/__tests__/createActionTypes-spec' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/src/__tests__/createReducer-spec' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/src/createActionTypes' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/src/createReducer' {
  declare module.exports: any;
}

declare module 'zeal-redux-utils/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zeal-redux-utils/lib/__tests__/createActionTypes-spec.js' {
  declare module.exports: $Exports<'zeal-redux-utils/lib/__tests__/createActionTypes-spec'>;
}
declare module 'zeal-redux-utils/lib/__tests__/createReducer-spec.js' {
  declare module.exports: $Exports<'zeal-redux-utils/lib/__tests__/createReducer-spec'>;
}
declare module 'zeal-redux-utils/lib/createActionTypes.js' {
  declare module.exports: $Exports<'zeal-redux-utils/lib/createActionTypes'>;
}
declare module 'zeal-redux-utils/lib/createReducer.js' {
  declare module.exports: $Exports<'zeal-redux-utils/lib/createReducer'>;
}
declare module 'zeal-redux-utils/lib/index.js' {
  declare module.exports: $Exports<'zeal-redux-utils/lib/index'>;
}
declare module 'zeal-redux-utils/src/__tests__/createActionTypes-spec.js' {
  declare module.exports: $Exports<'zeal-redux-utils/src/__tests__/createActionTypes-spec'>;
}
declare module 'zeal-redux-utils/src/__tests__/createReducer-spec.js' {
  declare module.exports: $Exports<'zeal-redux-utils/src/__tests__/createReducer-spec'>;
}
declare module 'zeal-redux-utils/src/createActionTypes.js' {
  declare module.exports: $Exports<'zeal-redux-utils/src/createActionTypes'>;
}
declare module 'zeal-redux-utils/src/createReducer.js' {
  declare module.exports: $Exports<'zeal-redux-utils/src/createReducer'>;
}
declare module 'zeal-redux-utils/src/index.js' {
  declare module.exports: $Exports<'zeal-redux-utils/src/index'>;
}
