// flow-typed signature: 6441f8f31252a4f9d6215a53034b52c2
// flow-typed version: <<STUB>>/@zeal/react-scripts_v0.1.9/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeal/react-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeal/react-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@zeal/react-scripts/bin/react-scripts' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/env' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/jest/CSSStub' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/jest/FileStub' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/jest/transform' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/paths' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/polyfills' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/scripts/build' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/scripts/eject' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/scripts/init' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/scripts/start' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/scripts/test' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/template/src/App' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/template/src/App.test' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/template/src/index' {
  declare module.exports: any;
}

declare module '@zeal/react-scripts/utils/createJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module '@zeal/react-scripts/bin/react-scripts.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/bin/react-scripts'>;
}
declare module '@zeal/react-scripts/config/env.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/env'>;
}
declare module '@zeal/react-scripts/config/jest/CSSStub.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/jest/CSSStub'>;
}
declare module '@zeal/react-scripts/config/jest/FileStub.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/jest/FileStub'>;
}
declare module '@zeal/react-scripts/config/jest/transform.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/jest/transform'>;
}
declare module '@zeal/react-scripts/config/paths.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/paths'>;
}
declare module '@zeal/react-scripts/config/polyfills.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/polyfills'>;
}
declare module '@zeal/react-scripts/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/webpack.config.dev'>;
}
declare module '@zeal/react-scripts/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/config/webpack.config.prod'>;
}
declare module '@zeal/react-scripts/scripts/build.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/scripts/build'>;
}
declare module '@zeal/react-scripts/scripts/eject.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/scripts/eject'>;
}
declare module '@zeal/react-scripts/scripts/init.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/scripts/init'>;
}
declare module '@zeal/react-scripts/scripts/start.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/scripts/start'>;
}
declare module '@zeal/react-scripts/scripts/test.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/scripts/test'>;
}
declare module '@zeal/react-scripts/template/src/App.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/template/src/App'>;
}
declare module '@zeal/react-scripts/template/src/App.test.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/template/src/App.test'>;
}
declare module '@zeal/react-scripts/template/src/index.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/template/src/index'>;
}
declare module '@zeal/react-scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'@zeal/react-scripts/utils/createJestConfig'>;
}
